node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     checkout scm
     docker.withRegistry('https://quay.io/repository/', 'f0a4505c-9429-4517-a5d1-f560e9854d1c') {
       def app = docker.build("jad_haj/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
